# Generated by Django 4.2.7 on 2023-11-28 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Title',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_type', models.CharField(max_length=50)),
                ('primary_title', models.CharField(max_length=255)),
                ('original_title', models.CharField(max_length=255)),
                ('is_adult', models.BooleanField(default=False)),
                ('start_year', models.IntegerField(blank=True, null=True)),
                ('runtime_minutes', models.IntegerField(blank=True, null=True)),
                ('genres', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
