# Generated by Django 4.2.7 on 2023-11-28 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('titles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='title',
            name='original_title',
            field=models.CharField(max_length=512),
        ),
        migrations.AlterField(
            model_name='title',
            name='primary_title',
            field=models.CharField(max_length=512),
        ),
    ]
