# Generated by Django 4.2.7 on 2023-12-05 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('titles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='title',
            name='average_review',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
