# Generated by Django 4.2.7 on 2023-12-07 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('titles', '0002_title_average_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='title',
            name='average_review',
            field=models.FloatField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='title',
            name='genres',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='title',
            name='is_adult',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='title',
            name='primary_title',
            field=models.CharField(db_index=True, max_length=512),
        ),
        migrations.AlterField(
            model_name='title',
            name='runtime_minutes',
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='title',
            name='start_year',
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='title',
            name='title_type',
            field=models.CharField(db_index=True, max_length=50),
        ),
    ]
